services:
  backend:
    build: backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  frontend:
    build: frontend
    ports:
      - '5173:5173'
  mongo:
    image: mongodb/mongodb-community-server
    ports:
      - '27017:27017'
